{% set name = "apache-airflow-providers-discord" %}
{% set version = "3.9.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_discord-{{ version }}.tar.gz
  sha256: d0f5c93899fee8c27445979096f38feb39ee17a5351cf07279d990d9dd87942e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - python >={{ python_min }},<4.dev0
    - apache-airflow >=2.9.0
    - apache-airflow-providers-common-compat >=1.6.0
    - apache-airflow-providers-http

test:
  imports:
    - airflow.providers.discord
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-discord for Apache Airflow
  license: Apache-2.0
  license_file: src/airflow/providers/discord/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-discord/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
